### ISSUE TITLE
Run a spellcheck on the entire website

### ISSUE THREAD

**Issue by Sumeshks29** [tvarit-foggy/tvarit.com#445]

**Comment by digitalwebair** [comment]
The result after Run a Spell Check

Die-casting		die casting
Tvarit
Blogs		Blog bogs blobs bloc's blows
ready-to-use
state-of-the-art
user-oriented		user oriented
real-time		real time
use-cases		use cases
AI-based	abased	abused
Real-Time
Uptime	up time	optima epitome
Die-Casting
frontend		front end fronted fro tend fronting frond
IIoT		Ito It it iota
on-premise		on premise
self-optimization		self optimization
self-configuration		self configuration
GmbH	Guam gm Cm gum

Plz have a look and let us know if we can make a change

**Comment by Poorvasisodia** [comment]
@Sumeshks29 please see in this spell check run case as digital webair has asked for a confirmation from our side.

**Comment by Poorvasisodia** [comment]
@digitalwebair @Sumeshks29 the words on the complete left side, I guess that's the right one that we have to select. So by going through this I found them ok. What else is needed here to close this issue.?

**Comment by digitalwebair** [comment]
@Poorvasisodia complete left side are the words we are having in website for eg. Die-casting; but by looking at spell check it says we have to remove hyphene from words which looks wrong.
