### ISSUE TITLE
Download Use case is not working 

### ISSUE THREAD

**Issue by Sumeshks29** [tvarit-foggy/tvarit.com#450]
The Download use case button in the below pages are not working. 

https://tvarit.com/optimize-oee-for-steel-and-metal-manufacturing-companies
https://tvarit.com/predictive-maintenance-for-industrial-electric-motors
https://tvarit.com/ai-based-production-solution-for-cable-manufacturing
https://tvarit.com/predictive-quality-for-die-casting-machines

Workflow:
1. Click on Download use case
2. Fill the Form and submit
3. Confirmation message that the download link will be sent to the given mail id
4. Send mail with link to respective use case.

**Comment by Poorvasisodia** [comment]
Yeah, but that's the point. Even we if put all information, neither we receive any email nor we can download the use case. Once we click on the submit icon, it's just moving.
