### ISSUE TITLE
Contact form Error

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#451]
The contact form submission link is not responding. While we input our details and click on submit, it shows a continued synchronizing option but then nothing works. Neither we receive any acknowledgment mail nor it shows any 'submitted' option.
![Contact form](https://user-images.githubusercontent.com/73514628/97259082-f5285700-183f-11eb-8915-681b577e12d9.png)

**Comment by Poorvasisodia** [comment]
@Sumeshks29 ..any update on this?

**Comment by rkamath3** [comment]
This is a critical error. Should be considered a P1. 

**Rationale**: This is the first entry point for all the leads generated. 


![image](https://user-images.githubusercontent.com/8947186/97838784-3063d380-1ce1-11eb-89b0-8473165b92fd.png)

**Comment by Sumeshks29** [comment]
@digitalwebair Please fix this on highest priority
