### ISSUE TITLE
URL broken

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#453]
While we open this page, there shows some bug on the top left corner as if the URL is broken.
Also, i just randomly did a site audit, here is the link below which states there are many broken links(maybe it's a bit technical so it is possible that I may have misunderstood some information. Please have a look.
https://validator.w3.org/checklink?uri=https%3A%2F%2Fwww.tvarit.com%2F&summary=on&hide_type=all&recursive=on&depth=5&check=Check
![Broken url](https://user-images.githubusercontent.com/73514628/97259610-353c0980-1841-11eb-9fc6-8d595169bf4d.png)

**Comment by digitalwebair** [comment]
The URL we checked doesn't work, doesn't show any further results. It shows up in loading and does nothing.

**Comment by Poorvasisodia** [comment]
@digitalwebair Please confirm if all the links are checked and they aren't broken anymore. Also did you went through the link I mentioned above.?
