### ISSUE TITLE
Repetition/similiarity of content meaning

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#455]
there is a summary that appears on the left side of the website at many pages. I found that there is a repetition of content lines "Therefore we at Tvarit AI relentlessly work to make your business.....
Again in the next para, "Therefore we at Tvarit AI relentlessly work to make your business and life simpler and upgraded." Also if you notice there is a similiarity in both the para sentence. 
![Content repetition](https://user-images.githubusercontent.com/73514628/97260204-78e34300-1842-11eb-8d89-3641f5d8b8ee.png)

**Comment by Sumeshks29** [comment]
The content to removed is in footer.php

**Comment by Poorvasisodia** [comment]
So is that possible or not.?

**Comment by Sumeshks29** [comment]
> So is that possible or not.?
Yes it is, the comment was @digitalwebair

**Comment by Poorvasisodia** [comment]
@digitalwebair @Sumeshks29 Please find here the correct content. I have just formatted the few lines which were showing repetition. U can use this script now
![image](https://user-images.githubusercontent.com/73514628/98438154-55f04300-210e-11eb-849a-a4410195690d.png)

**Comment by Poorvasisodia** [comment]
@digitalwebair ..this is still pending

**Comment by Poorvasisodia** [comment]
@Sumeshks29 As we saw yesterday that this issue was resolved, when I see this in Beta, the error is still there. Should I consider this issue as opened or closed?

**Comment by digitalwebair** [comment]
@Poorvasisodia should we work on it or not?

**Comment by Poorvasisodia** [comment]
Yes. We need to update bullet points(the way I have mentioned in the comment section of the issue number) in both German as well as English websites.

Poorva.

________________________________
