### ISSUE TITLE
Xing link is not re-directed to Xing profile

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#456]
Since I understand we don't have an account on Xing, while we click on the Xing icon, it is not re-directed to the social media profile on Xing page.
https://www.tvarit.com/about#Team- On this page
https://www.xing.com/companies.

**Comment by Poorvasisodia** [comment]
@Sumeshks29 we can close this as of now. It will be taken care of internally once confirmed

**Comment by Sumeshks29** [comment]
@digitalwebair Remove Xing icon from website

**Comment by Poorvasisodia** [comment]
@digitalwebair Is the Xing icon removed from the website as asked by Sumesh?
@Sumeshks29 IS there anything required to be done internally to get the Xing icon removed from the Website?

**Comment by Sumeshks29** [comment]
> @digitalwebair Is the Xing icon removed from the website as asked by Sumesh?
![Uploading image.png…]()
its not yet removed
> @Sumeshks29 IS there anything required to be done internally to get the Xing icon removed from the Website?
nope

**Comment by digitalwebair** [comment]
#526
