### ISSUE TITLE
No latest linkedin update on News page

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#459]
https://www.tvarit.com/news. When we enter into this page, the latest update of LinkedIn post is limited to December 2019 and not any after that.
![News page](https://user-images.githubusercontent.com/73514628/97261106-2c990280-1844-11eb-89f9-88f43e36bc0f.png)

**Comment by Poorvasisodia** [comment]
@Sumeshks29 is this to be done internally or the web designers take care of updating news/posts regularly on the website??

**Comment by Sumeshks29** [comment]
> @Sumeshks29 is this to be done internally or the web designers take care of updating news/posts regularly on the website??

@digitalwebair Please follow our Linked page and update the news section regularly based on new posts. 
@Poorvasisodia Please guide @digitalwebair on selecting the posts which needs to be added on the site.

**Comment by Poorvasisodia** [comment]
@Sumeshks29 Please close this too..

**Comment by starkblaze01** [comment]
As per discussion with Alessandra, only the Important New Headlines will be on the Main Website, the LinkedIn + Other Social Media Feed comes under the new revamp Plan, This issue listed under the new planning draft.

Closing the issue here. Thanks!

**Comment by Poorvasisodia** [comment]
Ok

________________________________
