### ISSUE TITLE
Spell check in videos

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#461]
https://www.tvarit.com/videos
Please check if we can change the spell mistake in the video. It appears when we click on to play the video from the icons given. 
![Spell error in video](https://user-images.githubusercontent.com/73514628/97261594-23f4fc00-1845-11eb-8a8c-bbb76a7b6f69.png)

**Comment by Sumeshks29** [comment]
@Poorvasisodia This has to be resolved from our youtube page.
