### ISSUE TITLE
Imprint page in German language in English version on Website

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#462]
The imprint page on English version of the website still opens in German language and then the webpage ask for translation online option. Please check.
![imprint](https://user-images.githubusercontent.com/73514628/97261837-b1385080-1845-11eb-8c16-64fec4e98898.png)

**Comment by Sumeshks29** [comment]
@Poorvasisodia please provide translation for this page.

**Comment by Poorvasisodia** [comment]
The English translation of this page is available but it appears once you select the google language automatic translation option. Isn't it possible that It can come directly into English, the moment we land on this page since we have selected the English view of the Website
![Imprint error](https://user-images.githubusercontent.com/73514628/97524591-0ea9da00-19cb-11eb-8826-bf5121ff761c.png)

**Comment by Sumeshks29** [comment]
@Poorvasisodia It is possible but you have to provide the content in english so that @digitalwebair can create a page for english version. You may speak with Harsh regarding the same. He had provided english content for privacy and poilicy.

**Comment by Poorvasisodia** [comment]
But the English content is already available on the website. It's just that in the German version the page directly appears in the German language as it has to be. But when we look into the English version - imprint- here also it appears in german language. When u click on a website google translate pop-up. then it is readable in English. The agency might have to only correct this error.

**Comment by Poorvasisodia** [comment]
To close till we receive an update.
