### ISSUE TITLE
German and english Website Corrections

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#476]
[Website Feedback (1).xlsx](https://github.com/tvarit-foggy/tvarit.com/files/5491861/Website.Feedback.1.xlsx)

As discussed, kindly resolve the issues starting with the German version

**Comment by Poorvasisodia** [comment]
[Website Feedback (4).xlsx](https://github.com/tvarit-foggy/tvarit.com/files/5588527/Website.Feedback.4.xlsx)
@digitalwebair  Refer to the file again

Row 5, 22, 23 pending
Row 9: done wrong

**Comment by digitalwebair** [comment]
@Poorvasisodia pull request - german content change

**Comment by Poorvasisodia** [comment]
Row: 9, ok, 5 Ok, 23 ok, Row: 22 Please see the text is looking wierd. Its getting inside the picture
