### ISSUE TITLE
Add new bullet points in management team

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#480]
@digitalwebair please add new bullet points in the Management team  on https://beta.tvarit.com/about#Vision
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/73514628/98784749-94914080-2421-11eb-9365-b401809342fe.png)

**Comment by Poorvasisodia** [comment]
Let me know once it is done.! Else please contact in case if there is any doubt.

**Comment by Poorvasisodia** [comment]
Similiarly in the German page also, we have to add bullet points. The content is as below.

Update Bulletpoints Suhas Patel | https://beta.tvarit.com/de/about#Vision | New Bulletpoints:      15 Jahre Erfahrung beim Aufbau von Start-ups, u.a. neue Fabriken für Chemiefertigung, verdichtete Biobrennstoffe und Verpackungsmaschinen ​       Ehemaliger Präsident TiE Deutschland ​       Umfassende Arbeitserfahrung mit Fortune-500-Unternehmen wie Intel und Qualcomm
-- | -- | --
Update Bulletpoints Juergen Halt | https://beta.tvarit.com/de/about#Vision | New Bulletpoints:      Business Transformation Experte für die Fertigungsindustrie       Langjährige Führungspositionen bei SAP and HP  ​      Umfangreiche Forschungserfahrungen zusammen mit Fraunhofer Institut und Deutsche Forschungsgemeinschaft (DFG)
Update Bulletpoints Rahul Prajapat | https://beta.tvarit.com/de/about#Vision | New Bulletpoints:      Master of Engineering IIT Mumbai & TU Darmstadt  ​       Verschiedene Forschungsprojekte mit NASA, NTT, Linde, IFM  ​       Auszeichnungen von MIT GSW, Harvard Projekt Asien "

Looks like:-
![image](https://user-images.githubusercontent.com/73514628/98789238-09677900-2428-11eb-9ab6-fa0f3c902d0f.png)

**Comment by Poorvasisodia** [comment]
@digitalwebair the sentence in Suhas patel is in continuation and not separated with bullet points. Please check.
Points for Juergen are also not updated still.

**Comment by Poorvasisodia** [comment]
@digitalwebair Please update the German points in this way:-

Updated Bullet Points Suhas  Patel
New Bulletpoints: 
•	15 Jahre Erfahrung beim Aufbau von Start-ups, u.a. neue Fabriken für Chemiefertigung, verdichtete Biobrennstoffe und Verpackungsmaschinen  

•	Ehemaliger Präsident TiE Deutschland  


•	Umfassende Arbeitserfahrung mit Fortune-500-Unternehmen wie Intel und Qualcomm

Update Bulletpoints Juergen Halt
New Bulletpoints: 
•	Business Transformation Experte für die Fertigungsindustrie 

•	Langjährige Führungspositionen bei SAP and HP   

•	Umfangreiche Forschungserfahrungen zusammen mit Fraunhofer Institut und Deutsche Forschungsgemeinschaft (DFG) 

Updated Bullet points Rahul Prajapat
New Bullet Points:-
•	Master of Engineering IIT Mumbai & TU Darmstadt   

•	Verschiedene Forschungsprojekte mit NASA, NTT, Linde, IFM   

•	Auszeichnungen von MIT GSW, Harvard Projekt Asien "

**Comment by Poorvasisodia** [comment]
@digitalwebair  Update below points for English version also

Updated Bullet Points Suhas  Patel
New Bulletpoints: 
o	15 years of experience in building startups including greenfield factories in chemicals, densified bio-fuels and packing machine manufacturing 
o	Ex-President TiE Deutschland 
o	Working experience with Fortune 500 firms like Intel & Qualcomm

Update Bulletpoints Juergen Halt
New Bulletpoints: 
o	Business Transformation by utilizing R&D
o	Brings huge experience from SAP and HP
o	Research Background from Fraunhofer and Deutsche Forschungsgemeinschaft(DFG)

Updated Bullet points Rahul Prajapat
New Bullet Points:-
o	M.Tech from IIT Mumbai & TU Darmstadt
o	Work experience with NASA, NTT, Linde, IFM
o	Awards from MIT GSW, Harvard project for Asia

**Comment by digitalwebair** [comment]
@Poorvasisodia pull request - german content change

**Comment by Poorvasisodia** [comment]
@digitalwebair @Sumeshks29 I cant see any changes in beta for the german bullet points. Please check.
