### ISSUE TITLE
Update text in the german website Vision page

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#481]
Update | https://beta.tvarit.com/de/about#Vision | 
Old Text   Wir sind ein deutsches Unternehmen mit Sitz in Frankfurt und entwickeln individuelle KI-Lösungen für alle Arten von Fertigungsproblemen und datenwissenschaftlichen Anforderungen. Wir ermöglichen es Unternehmen, intelligente und fundierte Entscheidungen zu treffen, indem wir aus einem Meer von Daten verwertbare und wertvolle Erkenntnisse ableiten. Hierfür bieten wir einsatzbereite KI-Lösungen, unsere KI-Plattform und KI-Beratungsdienste zur erfolgreichen Umsetzung von Data Science und KI-Projekten. In letzter Zeit haben wir viele renommierte Auszeichnungen erhalten, in denen wir unter anderem als eines der innovativsten KI-Unternehmen in ganz Europa ausgezeichnet wurden.   

New Text:   
Wir glauben daran, dass es eine Grundtugend ist, bestehende Prozesse in Frage zu stellen und durch die Nutzung neuer Technologien besser zu werden. Der natürliche "Schwund" an wertvollen Unternehmensressourcen, hervorgerufen durch Wartungskosten, Ausschuss, Energie- und Qualitätsprobleme sowie die ineffiziente Verwaltung von Beständen, ist kein Status Quo, mit dem wir uns zufriedengeben. ​   Deshalb arbeiten wir mit unserer “Werkzeugbox” an über 160 eigens entwickelten algorithmischen Modulen, um mit Data Science und maschinellem Lernen wertvolle Erkenntnisse aus der zunehmenden Menge an industriellen Daten zu ziehen. ​   Dafür entwickeln wir benutzerfreundliche Software-Produkte, die es unseren Kunden ermöglichen, drohende Ausfälle und Qualitätsabweichungen frühzeitig zu erkennen, pro-aktiv zu handeln und datenbasiert bessere Entscheidungen zu treffen.
-- | -- | --

**Comment by Poorvasisodia** [comment]
this one is still pending. Please do the needfull

**Comment by digitalwebair** [comment]
@Poorvasisodia german about vision text change #481

**Comment by Poorvasisodia** [comment]
@Sumeshks29 @digitalwebair Please check swati. The heading "WER WIR SIND? is moving inside the image
