### ISSUE TITLE
Update new MS form on website

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#484]
@digitalwebair Please find here the new MS form. We have to replace the old one with this new form. 
https://forms.office.com/Pages/DesignPage.aspx#FormId=F3YGVM4aokS32fWTJ-8QbXKloF9Zy-tDtked7ynalh5UOThOUEZKUE1QMFQ1WDFBM1dJUTVFRUhWTyQlQCN0PWcu

Let me know if there are any doubts or queries in this.

https://tvarit.com/qualification- this is the website survey page. U will find the existing form here.

**Comment by digitalwebair** [comment]
@Poorvasisodia The requested URL was not found on this server.

**Comment by Poorvasisodia** [comment]
@Sumeshks29  What we can do in this case? The form and website link are properly working at my place but somehow swati cannot find the URL. Can you please help ?

**Comment by Poorvasisodia** [comment]
@digitalwebair  Hi Swati, please check now with the below link. Now it's working. You can replace the form.
https://beta.tvarit.com/qualification

**Comment by Poorvasisodia** [comment]
@digitalwebair Swati please ignore this. It has been updated already.
