### ISSUE TITLE
To update a Reference Video on our Website

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#491]
@digitalwebair Hi Swati, we are planning to upload the below mentioned Youtube Video on our Website.
The location will be:-
Home Page: below the Reference title and above all the icons.
The format will be:-

Video on the Left     Video Link:- 
![image](https://user-images.githubusercontent.com/73514628/100870975-85a02a00-34c5-11eb-9dc0-a0b31f70b6b6.png)

 Content on the right
Content will be:- "Tvarit has one of the best artificial intelligence technologies that I have ever seen"
Learn more on what Prof. Aitor Goti Elordi, Director of the Digital Industry chair of the University of Deusto, has to say about his experiences in working with Tvarit. 

Please feel free to have a word for any doubts or query before starting this. We can have a joint call also for further clarity.
![Video Location](https://user-images.githubusercontent.com/73514628/100870910-699c8880-34c5-11eb-8fab-1a1a6f86008e.png)

**Comment by digitalwebair** [comment]
@Poorvasisodia video link says no video available. Please provide us either corrected link.

**Comment by Poorvasisodia** [comment]
@Sumeshks29 its done. you can close this.
