### ISSUE TITLE
Remove Auto-suggestions from Tvarit Christmas page

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#515]
Hi Swati,

Please remove the auto suggestions from the Tvarit Christmas page Greeting Video. Once the video ends, either it should recommend only Company videos or it should ask to Auto-play the same video. 
The irrelevant video recommendation are not giving a good impression if someone is on the page.

**Comment by digitalwebair** [comment]
#526
