### ISSUE TITLE
change the orders of the blogs under Data science project

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#540]
Hi Lokesh,

We need to change the order of the blogs under Data science project title.
Please move Smart agents blog at the top and below to that it should be the blog Business understanding
![image](https://user-images.githubusercontent.com/73514628/103256589-d36c5d00-49b3-11eb-9674-a96f4a1a9530.png)

**Comment by lokeshmittaldev** [comment]
Hello Poorva

I have done the code and created PR
https://github.com/tvarit-foggy/tvarit.com/pull/541

Thanks

**Comment by lokeshmittaldev** [comment]
Hi Lokesh,

Always mention "Fixes #issue" do not only write #issue
@Poorva Mishra<mailto:poorva.mishra@tvarit.com> I have pushed it to the beta, please check and confirm.


Regards,

Nilesh Bagwe



Assistant Manager

Tvarit GmbH

Mob: +91 7302453968



Web: www.tvarit.com<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.tvarit.com%2F&data=04%7C01%7Cnilesh.bagwe%40tvarit.com%7C514c2351dc9b4ed226a208d875ada3f8%7C540676171ace44a2b7d9f59327ef106d%7C0%7C0%7C637388735934903385%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=S%2FTmB3WU%2B%2FKixX0QkzAn9Xqgo6LJ6KIVnw7C1SzSbYI%3D&reserved=0>



Tvarit GmbH

Geschäftsführer: Suhas Patel

Hanauer Landstraße 521,

60386 Frankfurt am Main

Germany

Registergericht: Frankfurt am Main | Handelsregisternummer: HR B 114845

IMPRESSUM

Die in dieser Email und deren Anlagen enthaltenen Informationen sind vertraulich und nur für den vorgesehenen Empfänger bestimmt. Jegliche unautorisierte Verbreitung, Verwendung oder das Kopieren dieser Nachricht und deren Anlagen sind nicht gestattet. Sollten Sie nicht der richtige Adressat sein oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und entfernen Sie diese Email umgehend aus Ihrem System. Tvarit GmbH übernimmt keine Haftung für die fehlerfreie und vollständige Übertragung dieser Nachricht.

DISCLAIMER

The information contained in this e-mail and any attachments are confidential, may be subject to legal privilege, and is intended solely for the use of the addressee. Any unauthorized dissemination or copying of this e-mail or its attachments, and any use or disclosure of any information contained in them, is strictly prohibited and may be illegal. If you have received this e-mail in error, please notify us immediately. The e-mail transmission and any attachments must be deleted from your system. Tvarit GmbH does not bear any responsibility for the accuracy or completeness of its transmission.

________________________________

**Comment by Poorvasisodia** [comment]
@Sumeshks29 good to go
