### ISSUE TITLE
German Website Blog page- Edge AI blog change

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#544]
1. In the section “Industry” please change Topic to Cross Industry.
a.	Under cross Industry please map the Blog “Adding A Competitive Edge With 'Edge AI'” 
b.     Change the title of this blog from “Automotive” to Cross-Industry
c.	Change the circle image in this blog like the blog from the English page. You can check that here.
https://www.tvarit.com/blogs/adding-a-competitive-edge-with-edge-ai

**Comment by lokeshmittaldev** [comment]
Hello Poorva

I have done the changes and created the PR
https://github.com/tvarit-foggy/tvarit.com/pull/545

Thanks

**Comment by Poorvasisodia** [comment]
@lokeshmittaldev  the circle image is still pending to be changed in this blog. Could you please do that as well?

**Comment by lokeshmittaldev** [comment]
Hello Poorav

I have done the changes and committed the code in same PR
https://github.com/tvarit-foggy/tvarit.com/pull/545

Thanks
