### ISSUE TITLE
Aligning content on webpage-german

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#550]
Hi Lokesh,

You need to align the content on German page-https://beta.tvarit.com/de/about#Vision.
The text should not get overlapped on the image.
Let me know if you need anything to accomplish the task.

**Comment by lokeshmittaldev** [comment]
Hello Poorva

I just done the task and created the PR
https://github.com/tvarit-foggy/tvarit.com/pull/551

Thanks

**Comment by Poorvasisodia** [comment]
@Sumeshks29 All ok from my side for this issue
