### ISSUE TITLE
Update the logo of DiMap on our Website

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#573]
Hi Lokesh,

We have to update this logo of DiMap on our website.
Logo:-
![DiMaP Logo_Datum](https://user-images.githubusercontent.com/73514628/105033909-c3114480-5a7e-11eb-942e-c0aa6d91c042.png)
To update at this place:- https://www.tvarit.com
![Associates   Partners](https://user-images.githubusercontent.com/73514628/105034004-e3d99a00-5a7e-11eb-88f2-75b08dd825a5.png)
Please take this into priority and let me know if there are any concerns.

**Comment by nileshbagwe** [comment]
@lokeshmittaldev
