### ISSUE TITLE
Update the Sr Software Developer on careers

### ISSUE THREAD

**Issue by Sumeshks29** [tvarit-foggy/tvarit.com#579]
Link to Sr Senior Developer.

https://tvarit.sharepoint.com/:b:/r/sites/careers/Shared%20Documents/01.%20Pre-Hiring/Job%20Descriptions/Sr.%20Software%20Developer/Sr.%20Software%20Developer_JD.pdf?csf=1&web=1&e=HELNzS

**Comment by Poorvasisodia** [comment]
[Sr. Software Developer_JD.pdf](https://github.com/tvarit-foggy/tvarit.com/files/5877896/Sr.Software.Developer_JD.pdf)

**Comment by lokeshmittaldev** [comment]
Hello Poorva

I done the task and created PR
https://github.com/tvarit-foggy/tvarit.com/pull/582

Thanks
