### ISSUE TITLE
Add New Job Description for the Data Scientist under german careers page

### ISSUE THREAD

**Issue by Sumeshks29** [tvarit-foggy/tvarit.com#608]
add new open position in https://tvarit.com/de/career

https://tvarit.sharepoint.com/:w:/r/sites/careers/Shared%20Documents/01.%20Pre-Hiring/Job%20Descriptions/ML%20JD/Job%20Description%20-%20Data%20Scientist%20%20-%20Tvarit.docx?d=wc87f3d7df94141b29b183ca8bdd4a0ab&csf=1&web=1&e=M37cY7 

add only the german part. keep the format same the other JD's on the page.

@Poorvasisodia Please look into this

**Comment by Poorvasisodia** [comment]
@lokeshmittaldev Add new Job position only on the German career page of the Website.https://tvarit.com/de/career
Below are the details.

Title : DATA SCIENTIST
Tvarit sucht Datenwissenschaftler, die unabhängig arbeiten und das Team für Projekte in der Fertigungsindustrie leiten können. Kann auch zur Beratung von Datenanalyse und Projektentwicklung beitragen.

Anforderungsprofil:

· Arbeiten Sie mit Vorgängen und Funktionen zusammen, um die DT / Analytics-Anforderungen zu ermitteln.

· Identifizieren Sie relevante interne und externe Datenquellen und Sets, die an mehreren Standorten abgebaut werden sollen, um die Geschäftsanforderungen zu erfüllen. Sammeln Sie große strukturierte und unstrukturierte Datensätze und Variablen.

· Verbessern und optimieren Sie die Datenerfassungsverfahren, um relevante Informationen für den Aufbau von Analysesystemen aufzunehmen.

· Wenden Sie Data Mining-Techniken an und führen Sie statistische Analysen mit modernsten Methoden in Sandbox- und Testumgebungen durch. Entwickeln und nutzen Sie Tools, Algorithmen, Prozesse und Modelle, um Big Data zu verarbeiten.

· Definieren Sie relevante Datenquellen und Strukturen, um Daten- und Fehleranalysen durchzuführen, um Modelle zu verbessern, Daten zu bereinigen und auf Einheitlichkeit und Genauigkeit zu validieren. Erstellen Sie automatisierte Anomalieerkennungssysteme und verfolgen Sie die Leistung ständig.

· Analysieren Sie Daten auf Trends und Muster. Interpretieren und kontextualisieren Sie Daten, um die Anforderungsspezifikation zu erfüllen. Fügen Sie nach Bedarf zusätzliche Datenquellen hinzu.

· Entwickeln, (neu) trainieren und warten Sie Modelle für maschinelles Lernen / KI, um große strukturierte / unstrukturierte Datenanalyseströme zu verarbeiten.

· Erstellen Sie verbrauchsfähige Vorhersagemodelle, die von Funktionen und Stakeholdern der Fertigung genutzt werden können, um den Betrieb, die Effizienz und die Vorhersageanalyse zu verbessern (z. B. Vorhersagequalität, vorausschauende Wartung, Rückverfolgbarkeit und Energieoptimierung)

· Dokumentieren und präsentieren Sie Analyseergebnisse mit wertvollen geschäftlichen Erkenntnissen. Spezifikation der technischen Anforderungen des Handwerks für Entwicklungszwecke.

· Bereitstellen von Predictive Analytics-Lösungen für die Fertigungsindustrie in der Produktion - Führen Sie den gesamten Prozess von der Erstellung und Optimierung von Algorithmen bis zur Operationalisierung des Modells in Workflows, um die Auswirkungen zu messen.

· Unterstützung und Orchestrierung der Lösungsbereitstellung gemäß der DT Data Analytics-Strategie Arbeiten Sie mit globalen und lokalen IT-Teams zusammen. Cloud-Architekten, Big-Data-Architekten, DevOps-Ressourcen und andere, um digitale Ökosysteme und integrierte Plattformen zu bilden, bereitzustellen, zu unterstützen und kontinuierlich zu verbessern.

· Kommunizieren Sie Lösungen für Datenanalysen an Stakeholder, fördern Sie die weltweite Akzeptanz im gesamten Unternehmen und implementieren Sie Verbesserungen an Betriebssystemen (Continuous Improvement Process).

Qualifikation und Erfahrung

· Masters / Bachelor of Engineering / gleichwertige Qualifikation

· Insgesamt 3+ Jahre Erfahrung mit 3 Jahren Erfahrung als Data Scientist mit 2 Jahren Erfahrung in der Fertigungsindustrie

· Erfahrung in der Automobilindustrie von Vorteil.Arbeitserfahrung in einem globalen Umfeld und funktionsübergreifenden Teams.

· Effektive Kommunikations- und Präsentationsfähigkeiten.

· Nachgewiesene Erfahrung mit einer Reihe von Techniken, Werkzeugen und Methoden in Bezug auf Datenmodellierung, Textanalyse und NLP (Natural Language Processing)Erfahrung mit Vorhersagemodellen - insbesondere mit vorausschauender Wartung, vorausschauender Qualität und Rückverfolgbarkeit.

· Fließend in Python und R. Beherrscht die Entwicklung von Algorithmen im Python-Ökosystem.Praktische Erfahrung mit einer Vielzahl von Analysemethoden (EDA, Maschinelles Lernen - überwacht, unbeaufsichtigt).Kenntnisse und Verständnis statistischer, prädiktiver Modellierungstechniken und -algorithmen, inkl. Neuronale Netze, Text- / Data-Mining, LDA, Entitätsextraktion, Klassifizierung, Zuordnungsregeln, Hashing, Ähnlichkeiten, GLM / Regression, Random Forest, Gradient Boosting, SVM usw.

· Verständnis der Amazon- und Microsoft Cloud IoT-Plattformen und -Toolsets.

· Starke Entscheidungskompetenz in Bezug auf Datenanalyse und muss in der Lage sein, Projekte unabhängig zu leiten.

ZertifizierungenSAS-zertifizierter Big Data-Experte / Data ScientistCloudera Certified Professional - Dateningenieur.

Bei Interesse, bitte eine Bewerbung mit Lebenslauf an careers.de@tvarit.com senden

Standort: Frankfurt am Main

Keep the format similar to other title and descriptions that we have on the career page.

**Comment by starkblaze01** [comment]
Postiton Filled
