### ISSUE TITLE
To replace Tvarit superscript with the image form. 

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#656]
@lokeshmittaldev , As done earlier, please find below excel sheet which consist of all pages link and the Text which has to be replaced with the attached Tvarit Superscript image.

First three are Raleway Extra Bold font and rest 3 are Raleway Black font-Whichever suits well and is working with the rest of the fonts.

Feel free to reach me out in case of any doubt.

[Page link to add superscript.xlsx](https://github.com/tvarit-foggy/tvarit.com/files/6162816/Page.link.to.add.superscript.xlsx)
![Tvarit BIG R logo- Black-8](https://user-images.githubusercontent.com/73514628/111603946-d892b880-87fa-11eb-812f-82729a54f1de.png)
![Tvarit BIG R logo- Red-8](https://user-images.githubusercontent.com/73514628/111603952-d9c3e580-87fa-11eb-87ef-cb96036309bd.png)
![Tvarit BIG R logo- white-8](https://user-images.githubusercontent.com/73514628/111603953-d9c3e580-87fa-11eb-856a-1fb7f8510ee7.png)
![Tvarit BIG R Black logo- Black-100](https://user-images.githubusercontent.com/73514628/111603982-dfb9c680-87fa-11eb-89e2-f6cfe092fc38.jpg)
![Tvarit BIG R Black logo- Red-100](https://user-images.githubusercontent.com/73514628/111603984-e0525d00-87fa-11eb-84b6-dca524057fa1.jpg)
![Tvarit BIG R Black logo- white-100](https://user-images.githubusercontent.com/73514628/111603988-e0eaf380-87fa-11eb-9791-61a4ba58cc44.jpg)

@lokeshmittaldev Please add this code whenever you create PR for this issue---> [CMW-27]

[CMW-27]: https://tvarit.atlassian.net/browse/CMW-27

**Comment by starkblaze01** [comment]
Closing as the main website changed.
