### ISSUE TITLE
Add new Job Position on the Website (English)

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#660]
Title : HUMAN RESOURCE MANAGER (BARODA - GUJARAT)

Job description: as below:
[HR Manager.docx](https://github.com/tvarit-foggy/tvarit.com/files/6196664/HR.Manager.docx)
Please cross-check twice before generating PR.
The format should be the same.
Inside the JD, in location-mentioned Baroda (Gujarat)

**Comment by lokeshmittaldev** [comment]
https://github.com/tvarit-foggy/tvarit.com/pull/661
