### ISSUE TITLE
Correction in spelling and title bar

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#769]
Remove steel from the title bar heading and also correct the word- ALUMINIUM

Refer image for reference
![image](https://user-images.githubusercontent.com/73514628/121512779-b5e1fb80-ca07-11eb-8827-6ef90647b536.png)

**Comment by Poorvasisodia** [comment]
@starkblaze01 Please hold the issue till I confirm

**Comment by starkblaze01** [comment]
Closing as the main website changed
